# this is only for search engines, it does not appear in the home
# as long as the json variables name and description are provided
title: AntiFractal
description: Jekyll based personal landing page
baseurl: ""
url: https://antifractal.com

# this information is shown on the homepage, all fields are optional and
# can be declared either as a single string or as a string array/hash
json:
  name: timothy klumpner
  description:
    - This tiny website
    - Is the landing page
    - For all my projects
  cv: assets/cv.pdf
  resume: assets/resume.pdf
  projects:
    - title: AntiFractal
      link: https://antifractal.com
      blurb: jekyll powered landing page

    - title: philosophy garden
      link: https://garden.antifractal.com
      blurb: pseudo-blog knowledge base

    - title: oral history archive
      link: https://archive.antifractal.com
      blurb: PEVN-stack CRUD project

  contact:
    email: tj.klumpner@gmail.com
  profiles:
    linkedin: https://www.linkedin.com/in/timothy-klumpner-304002244/
    github: https://github.com/DeltaCeph

exclude:
  - LICENSE
  - README.md

plugins:
  - jekyll-seo-tag
  - jekyll-sitemap

whitelist:
  - jekyll-sitemap

sass:
  sass_dir: _sass
  style: compressed
  sourcemap: never
